# Generated by Django 4.2.27 on 2026-07-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_adminauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_stores_module', 'Can access stores module'), ('access_products_module', 'Can access products module'), ('access_inventory_module', 'Can access inventory module'), ('access_customers_module', 'Can access customers module'), ('access_orders_module', 'Can access orders module'), ('access_delivery_module', 'Can access delivery module'))},
        ),
    ]
