# Generated by Django 5.2.16 on 2026-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('ADMIN_CREATED', 'Admin Created'), ('ADMIN_UPDATED', 'Admin Updated'), ('ADMIN_ACTIVATED', 'Admin Activated'), ('ADMIN_DEACTIVATED', 'Admin Deactivated'), ('GROUP_ASSIGNED', 'Group Assigned'), ('GROUP_REMOVED', 'Group Removed'), ('PERMISSION_ASSIGNED', 'Permission Assigned'), ('PERMISSION_REMOVED', 'Permission Removed'), ('STORE_CREATED', 'Store Created'), ('STORE_UPDATED', 'Store Updated'), ('STORE_STATUS_CHANGED', 'Store Status Changed'), ('STORE_USER_CREATED', 'Store User Created'), ('STORE_USER_UPDATED', 'Store User Updated'), ('STORE_USER_ACTIVATED', 'Store User Activated'), ('STORE_USER_DEACTIVATED', 'Store User Deactivated'), ('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_STATUS_CHANGED', 'Product Status Changed'), ('PRODUCT_PRICING_CHANGED', 'Product Pricing Changed'), ('INVENTORY_STOCK_IN', 'Inventory Stock In'), ('INVENTORY_STOCK_OUT', 'Inventory Stock Out'), ('INVENTORY_ADJUSTED', 'Inventory Adjusted'), ('INVENTORY_DAMAGE_RECORDED', 'Inventory Damage Recorded'), ('INVENTORY_EXPIRY_RECORDED', 'Inventory Expiry Recorded'), ('PURCHASE_ENTRY_CONFIRMED', 'Purchase Entry Confirmed')], max_length=50),
        ),
    ]
