# Generated by Django 5.2.16 on 2026-07-30 06:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_approved_by_approved_at'),
        ('stores', '0004_store_portal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_purchase_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_entries', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_entries', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_entry_lines', to='catalog.product')),
                ('purchase_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase Stock-In'), ('STOCK_IN', 'Manual Stock-In'), ('STOCK_OUT', 'Manual Stock-Out'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('CUSTOMER_RETURN', 'Customer Return'), ('SUPPLIER_RETURN', 'Supplier Return')], max_length=32)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='stores.store')),
                ('purchase_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.purchaseentry')),
                ('purchase_entry_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.purchaseentryline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseentry',
            index=models.Index(fields=['store', '-created_at'], name='inventory_p_store_i_6ff1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseentry',
            index=models.Index(fields=['store', 'status'], name='inventory_p_store_i_71d909_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseentry',
            index=models.Index(fields=['entry_date'], name='inventory_p_entry_d_4780bf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseentry',
            index=models.Index(fields=['status', '-created_at'], name='inventory_p_status_65e811_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseentry',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', Decimal('0'))), name='purchase_entry_total_cost_non_negative'),
        ),
        migrations.AddIndex(
            model_name='purchaseentryline',
            index=models.Index(fields=['purchase_entry', 'product'], name='inventory_p_purchas_4428c3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseentryline',
            index=models.Index(fields=['product'], name='inventory_p_product_f7430e_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseentryline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='purchase_entry_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseentryline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0'))), name='purchase_entry_line_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseentryline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', Decimal('0'))), name='purchase_entry_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseentryline',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturing_date__isnull', True), ('expiry_date__isnull', True), ('expiry_date__gte', models.F('manufacturing_date')), _connector='OR'), name='purchase_line_expiry_on_or_after_manufacturing'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['store', '-created_at'], name='inventory_i_store_i_d11910_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', '-created_at'], name='inventory_i_product_c769c0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['store', 'transaction_type'], name='inventory_i_store_i_62b075_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='inventory_i_transac_307b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['purchase_entry'], name='inventory_i_purchas_acd557_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='inventory_transaction_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('previous_quantity__gte', Decimal('0'))), name='inventory_transaction_previous_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('new_quantity__gte', Decimal('0'))), name='inventory_transaction_new_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', Decimal('0')), _connector='OR'), name='inventory_transaction_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturing_date__isnull', True), ('expiry_date__isnull', True), ('expiry_date__gte', models.F('manufacturing_date')), _connector='OR'), name='inventory_txn_expiry_on_or_after_manufacturing'),
        ),
    ]
