# Generated by Django 5.2.16 on 2026-07-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at'], 'permissions': (('view_all_inventory', 'Can view inventory across all stores'), ('record_purchase', 'Can record purchase stock-in entries'), ('adjust_inventory', 'Can record manual inventory adjustments'), ('record_damage', 'Can record damaged stock'), ('record_expiry', 'Can record expired stock'), ('export_inventory', 'Can export inventory data'))},
        ),
    ]
