# Generated by Django 5.2.16 on 2026-07-31 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_approved_by_approved_at'),
        ('inventory', '0002_inventory_permissions_and_store_user_flag'),
        ('stores', '0005_inventory_permissions_and_store_user_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['reference'], name='inventory_i_referen_6e561a_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__startswith', 'order-item:')), fields=('reference',), name='inventory_txn_unique_order_item_reference'),
        ),
    ]
