# Generated by Django 5.2.16 on 2026-07-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'permissions': (('activate_customer', 'Can activate or deactivate customers'), ('verify_customer', 'Can verify or unverify customers'))},
        ),
    ]
