# Generated by Django 5.2.16 on 2026-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
    ]
