# Generated by Django 5.2.16 on 2026-07-29 17:12

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_product_slugs(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    used = {}
    for product in Product.objects.all().order_by("pk"):
        store_id = product.store_id
        used.setdefault(store_id, set())
        base = slugify(product.name) or "product"
        candidate = base
        suffix = 2
        while candidate in used[store_id]:
            candidate = f"{base}-{suffix}"
            suffix += 1
        used[store_id].add(candidate)
        if product.slug != candidate:
            product.slug = candidate
            product.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_product_catalogue"),
        ("stores", "0004_store_portal_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("PIECE", "Piece"),
                    ("PACK", "Pack"),
                    ("BOX", "Box"),
                    ("DOZEN", "Dozen"),
                    ("KG", "Kilogram"),
                    ("GRAM", "Gram"),
                    ("LITER", "Liter"),
                    ("ML", "Milliliter"),
                    ("METER", "Meter"),
                ],
                default="PIECE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="productpricehistory",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIXED", "Fixed"),
                    ("PERCENTAGE", "Percentage"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="productpricehistory",
            name="profit_margin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIXED", "Fixed"),
                    ("PERCENTAGE", "Percentage"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_product_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"),
                name="unique_slug_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_quantity__gte", Decimal("0"))),
                name="product_stock_quantity_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manufacturing_date__isnull", True),
                    ("expiry_date__isnull", True),
                    ("expiry_date__gte", models.F("manufacturing_date")),
                    _connector="OR",
                ),
                name="product_expiry_on_or_after_manufacturing",
            ),
        ),
    ]
