# Generated by Django 5.2.16 on 2026-09-13 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_approved_by_approved_at'),
        ('stores', '0006_storeuser_can_manage_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('template_version', models.CharField(default='v1', max_length=16)),
                ('csv_bytes', models.BinaryField()),
                ('csv_sha256', models.CharField(editable=False, max_length=64)),
                ('image_bundle_key', models.UUIDField(editable=False, null=True)),
                ('image_manifest', models.JSONField(default=dict, editable=False)),
                ('fingerprint', models.CharField(editable=False, max_length=64, null=True)),
                ('approved_snapshot', models.JSONField(editable=False, null=True)),
                ('approval_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Awaiting operator — image preparation'), ('PREPARING', 'Preparing images'), ('INVALID', 'Validation errors'), ('READY', 'Ready for review'), ('AWAITING_OPERATOR', 'Import approved — Awaiting operator'), ('RUNNING', 'Executing'), ('PAUSED', 'Paused — operator attention required'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('DUPLICATE', 'Duplicate submission')], default='UPLOADED', max_length=32)),
                ('lease_token', models.UUIDField(editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_catalog_imports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_catalog_imports', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_submissions', to='catalog.importjob')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_catalog_imports', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('approve_importjob', 'Can approve import execution'), ('execute_importjob', 'Can prepare and execute imports')],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('external_sku', models.CharField(max_length=64, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('row_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('INVALID', 'Invalid'), ('READY', 'Ready'), ('RUNNING', 'Unresolved attempt'), ('SUCCEEDED', 'Created — pending product approval'), ('FAILED', 'Failed'), ('ALREADY_IMPORTED', 'Already imported — unchanged')], default='READY', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_import_row_attempts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='catalog.importjob')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_receipts', to='catalog.product')),
            ],
            options={
                'ordering': ['row_number'],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['store', '-created_at'], name='cat_imp_store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', '-created_at'], name='cat_imp_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(fields=('fingerprint',), name='cat_imp_job_fingerprint_uq'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['UPLOADED', 'PREPARING', 'INVALID', 'READY', 'AWAITING_OPERATOR', 'RUNNING', 'PAUSED', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'DUPLICATE'])), name='cat_imp_job_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['READY', 'AWAITING_OPERATOR', 'RUNNING', 'PAUSED', 'COMPLETED', 'COMPLETED_WITH_ERRORS']), _negated=True), models.Q(('fingerprint__isnull', False), ('image_bundle_key__isnull', False), models.Q(('fingerprint', ''), _negated=True)), _connector='OR'), name='cat_imp_job_ready_bundle_ck'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['AWAITING_OPERATOR', 'RUNNING', 'PAUSED', 'COMPLETED', 'COMPLETED_WITH_ERRORS']), _negated=True), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('approved_snapshot__isnull', False), models.Q(('approved_snapshot', {}), _negated=True), models.Q(('approval_hash', ''), _negated=True)), _connector='OR'), name='cat_imp_job_approval_ck'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('operator__isnull', False), ('status__in', ['PREPARING', 'RUNNING'])), models.Q(models.Q(('status__in', ['PREPARING', 'RUNNING']), _negated=True), ('lease_expires_at__isnull', True), ('lease_token__isnull', True)), _connector='OR'), name='cat_imp_job_lease_ck'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duplicate_of__isnull', False), ('fingerprint__isnull', True), ('status', 'DUPLICATE'), models.Q(('duplicate_of', models.F('id')), _negated=True)), models.Q(models.Q(('status', 'DUPLICATE'), _negated=True), ('duplicate_of__isnull', True)), _connector='OR'), name='cat_imp_job_duplicate_ck'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['job', 'status', 'row_number'], name='cat_imp_rows_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('job', 'row_number'), name='cat_imp_row_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('job', 'external_sku'), name='cat_imp_row_sku_uq'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUCCEEDED')), fields=('product',), name='cat_imp_created_receipt_uq'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='cat_imp_row_number_ck'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['INVALID', 'READY', 'RUNNING', 'SUCCEEDED', 'FAILED', 'ALREADY_IMPORTED'])), name='cat_imp_row_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'INVALID'), models.Q(('external_sku__isnull', False), models.Q(('external_sku', ''), _negated=True)), _connector='OR'), models.Q(models.Q(('status__in', ['RUNNING', 'SUCCEEDED', 'FAILED', 'ALREADY_IMPORTED']), _negated=True), models.Q(('row_fingerprint', ''), _negated=True), _connector='OR')), name='cat_imp_row_identity_ck'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('executed_by__isnull', False), ('product__isnull', False), ('status__in', ['SUCCEEDED', 'ALREADY_IMPORTED'])), models.Q(models.Q(('status__in', ['SUCCEEDED', 'ALREADY_IMPORTED']), _negated=True), ('product__isnull', True)), _connector='OR'), name='cat_imp_row_receipt_ck'),
        ),
    ]
