# Generated by Django 5.2.16 on 2026-10-08 13:02

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_search_trigrams'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='display_image',
            field=models.ImageField(blank=True, editable=False, upload_to=catalog.validators.product_image_upload_to),
        ),
    ]
