# Generated by Django 5.2.16 on 2026-10-09 03:54

import catalog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productimage_display_image'),
        ('stores', '0006_storeuser_can_manage_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=200)),
                ('source_hash', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.photoimportbatch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['source_key', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PhotoImportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog-import/%Y/%m/', validators=[catalog.validators.validate_product_image])),
                ('sha256', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.photoimportitem')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='photoimportitem',
            constraint=models.UniqueConstraint(fields=('batch', 'source_key'), name='unique_photo_import_group'),
        ),
        migrations.AddConstraint(
            model_name='photoimportimage',
            constraint=models.UniqueConstraint(fields=('item', 'sha256'), name='unique_import_photo'),
        ),
    ]
