# Generated by Django 5.2.16 on 2026-10-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_photoimportbatch_photoimportitem_photoimportimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoimportimage',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
