# Generated by Django 5.2.16 on 2026-10-09 04:54

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_photoimportimage_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimportimage',
            name='image',
            field=models.ImageField(upload_to=catalog.validators.product_image_upload_to, validators=[catalog.validators.validate_product_image]),
        ),
    ]
