# Generated by Django 5.2.16 on 2026-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-facing final price when the line was last updated. Used only to detect price changes in the cart UI.', max_digits=12, null=True),
        ),
    ]
