# Generated by Django 5.2.16 on 2026-07-29 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['country', 'state', 'city', 'line1'],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), name='address_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), name='address_longitude_range')],
            },
        ),
    ]
