# Generated by Django 5.2.16 on 2026-07-29 04:59

import django.core.validators
import django.db.models.deletion
import stores.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'store categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('store_code', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('store_type', models.CharField(choices=[('OWN_STORE', 'Own Store'), ('PARTNER_STORE', 'Partner Store'), ('PARTNER_HOME', 'Partner Home')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/', validators=[stores.validators.validate_store_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store', to='locations.address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stores', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.storecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('manage_store_users', 'Can manage store users'), ('change_store_status', 'Can change store status')),
            },
        ),
        migrations.CreateModel(
            name='StoreStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], max_length=32)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_status_changes', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'store status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_users', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_users', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percentage__gte', Decimal('0')), ('commission_percentage__lte', Decimal('100'))), name='store_commission_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='storeuser',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_user_pair'),
        ),
        migrations.AddConstraint(
            model_name='storeuser',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_store_assignment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='storeuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('store',), name='unique_primary_store_user_per_store'),
        ),
    ]
