# Generated by Django 5.2.16 on 2026-07-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_image_upload_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'permissions': (('approve_store', 'Can approve or reject stores'), ('suspend_store', 'Can suspend stores'))},
        ),
    ]
