# Generated by Django 5.2.16 on 2026-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
