# Generated by Django 5.2.16 on 2026-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_portal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='can_manage_inventory',
            field=models.BooleanField(default=True, help_text='When True, this store user may change inventory for their store.'),
        ),
    ]
