# Generated by Django 5.2.16 on 2026-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_inventory_permissions_and_store_user_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='can_manage_orders',
            field=models.BooleanField(default=True, help_text='When True, this store user may accept, reject and progress store orders.'),
        ),
    ]
