# Generated by Django 5.2.16 on 2026-07-31 09:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_approved_by_approved_at'),
        ('customers', '0003_address_landmark_district_and_delivery_instructions'),
        ('locations', '0002_address_landmark_district_and_delivery_instructions'),
        ('stores', '0005_inventory_permissions_and_store_user_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=32)),
                ('fulfillment_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('FACILITY_PICKUP', 'Facility Pickup')], max_length=32)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery')], default='COD', max_length=32)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('checkout_token', models.CharField(help_text='Idempotency key supplied at checkout to prevent duplicate orders.', max_length=64, unique=True)),
                ('delivery_recipient_name', models.CharField(blank=True, max_length=150)),
                ('delivery_phone_number', models.CharField(blank=True, max_length=20)),
                ('delivery_line1', models.CharField(blank=True, max_length=255)),
                ('delivery_line2', models.CharField(blank=True, max_length=255)),
                ('delivery_landmark', models.CharField(blank=True, max_length=255)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_district', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_country', models.CharField(blank=True, max_length=100)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('items_subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('customer_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customeraddress')),
            ],
            options={
                'ordering': ['-placed_at', '-created_at'],
                'permissions': (('manage_order_status', 'Can manage order status'), ('manage_payment_status', 'Can manage order payment status'), ('view_all_orders', 'Can view orders across all customers and stores')),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('new_status', models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'order status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_locations', to='locations.address')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_locations', to='stores.store')),
            ],
            options={
                'ordering': ['store__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_order_number', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('store_name', models.CharField(max_length=200)),
                ('store_code', models.CharField(max_length=32)),
                ('items_subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('store_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='orders.order')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='orders.pickuplocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='stores.store')),
            ],
            options={
                'ordering': ['order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=32)),
                ('sku', models.CharField(max_length=64)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('PACK', 'Pack'), ('BOX', 'Box'), ('DOZEN', 'Dozen'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITER', 'Liter'), ('ML', 'Milliliter'), ('METER', 'Meter')], max_length=16)),
                ('unit_value', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Customer-facing unit price (Product.final_price) at checkout.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('store_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.storeorder')),
            ],
            options={
                'ordering': ['store_order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], max_length=32)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('store_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='orders.storeorder')),
            ],
            options={
                'verbose_name_plural': 'store order status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-placed_at'], name='orders_orde_custome_7b68ab_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='orders_orde_status_ab153f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-placed_at'], name='orders_orde_payment_18b19e_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('items_subtotal__gte', Decimal('0'))), name='order_items_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_charge__gte', Decimal('0'))), name='order_delivery_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total__gte', Decimal('0'))), name='order_discount_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', Decimal('0'))), name='order_grand_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pickuplocation',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('store', 'code'), name='unique_pickup_location_code_per_store'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', '-created_at'], name='orders_stor_store_i_45190b_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['status', '-created_at'], name='orders_stor_status_7b9815_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeorder',
            constraint=models.UniqueConstraint(fields=('order', 'store'), name='unique_store_order_per_order_store'),
        ),
        migrations.AddConstraint(
            model_name='storeorder',
            constraint=models.CheckConstraint(condition=models.Q(('items_subtotal__gte', Decimal('0'))), name='store_order_items_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='storeorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_charge__gte', Decimal('0'))), name='store_order_delivery_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='storeorder',
            constraint=models.CheckConstraint(condition=models.Q(('store_total__gte', Decimal('0'))), name='store_order_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_code'], name='orders_orde_product_468aaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0'))), name='order_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', Decimal('0'))), name='order_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_value__gte', Decimal('0'))), name='order_item_unit_value_non_negative'),
        ),
    ]
