# Generated by Django 5.2.16 on 2026-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='hours',
            field=models.CharField(blank=True, help_text='Customer-facing pickup hours, e.g. Mon–Sat 9:00–20:00.', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PAY_AT_PICKUP', 'Pay at Pickup')], default='COD', max_length=32),
        ),
    ]
