# Generated by Django 5.2.16 on 2026-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_pay_at_pickup_and_pickup_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_restored',
            field=models.BooleanField(default=False, help_text='True after checkout stock for this line has been restored. Prevents a second restoration on repeated cancel/reject.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
