# Generated by Django 5.2.16 on 2026-07-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_cancelled_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='True after the owning StoreOrder rejection marked this line rejected.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIALLY_CANCELLED', 'Partially Cancelled'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIALLY_CANCELLED', 'Partially Cancelled'), ('CANCELLED', 'Cancelled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PARTIALLY_CANCELLED', 'Partially Cancelled'), ('CANCELLED', 'Cancelled')], max_length=32),
        ),
    ]
