# Generated by Django 5.2.16 on 2026-07-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_partial_cancel_and_item_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_at', '-created_at'], 'permissions': (('manage_order_status', 'Can manage order status'), ('manage_payment_status', 'Can manage order payment status'), ('view_all_orders', 'Can view orders across all customers and stores'), ('cancel_order', 'Can cancel orders administratively'))},
        ),
    ]
